theme: jekyll-theme-Midnight

title: "Alpha-Bet"
description: ""
show_downloads: false
favicon: /favicon.ico

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

github:
  is_project_page: false
  is_user_page: true
  repository_url: "https://alpha-bet-writeups.github.io/"
  owner_name: "Alpha-Bet"
  owner_url: "https://alpha-bet-writeups.github.io/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
