show_downloads: false
show_metadata: true

theme: jekyll-theme-primer

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      read_time: true
      toc: true
