theme: jekyll-theme-Midnight

title: "Alpha-Bet"
description: "Expert cybersecurity write-ups focusing on infrastructure penetration testing, manual exploitation, real-world vulnerabilities, backdoors, privilege escalation, networking, and server security. Proficient in Python, Ruby, and Assembly."
show_downloads: false
favicon: /favicon.ico

author:
  name: "Alpha-Bet"

keywords: "Infrastructure Penetration Testing, Manual Exploitation, Real Vulnerabilities, Backdoors, Privilege Escalation, Network Security, Python, Ruby, Assembly, CTF Write-ups, Cybersecurity"

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

github:
  is_project_page: false
  is_user_page: true
  repository_url: "https://github.com/alpha-bet-404"
  owner_name: "Alpha-Bet"
  owner_url: "https://github.com/alpha-bet-404"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
